# Generated by Django 5.2.17 on 2026-09-01 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Home department. Blank for visiting or unaffiliated staff.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='academics.department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Degree program. Blank for a student not yet assigned one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.program', verbose_name='program'),
        ),
    ]
