# Generated by Django 5.2.17 on 2026-09-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_prerequisiterule_minimum_grade'),
        ('accounts', '0002_lecturerprofile_department_studentprofile_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed')], db_index=True, max_length=10, verbose_name='status')),
                ('waitlist_position', models.PositiveSmallIntegerField(blank=True, help_text='1 is next in line. Set only while status is WAITLISTED.', null=True, verbose_name='waitlist position')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], default='', help_text='Recorded once status is COMPLETED.', max_length=2, verbose_name='grade')),
                ('registered_at', models.DateTimeField(verbose_name='registered at')),
                ('dropped_at', models.DateTimeField(blank=True, null=True, verbose_name='dropped at')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['section', 'status'], name='registration_section_status'), models.Index(fields=['student', 'status'], name='registration_student_status')],
                'constraints': [models.UniqueConstraint(fields=('student', 'section'), name='registration_enrollment_unique'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'WAITLISTED'), ('waitlist_position__isnull', False)), models.Q(models.Q(('status', 'WAITLISTED'), _negated=True), ('waitlist_position__isnull', True)), _connector='OR'), name='registration_enrollment_waitlist_position_consistency'), models.CheckConstraint(condition=models.Q(('status', 'COMPLETED'), ('grade', ''), _connector='OR'), name='registration_enrollment_grade_requires_completed')],
            },
        ),
    ]
