# Generated by Django 5.2.17 on 2026-09-01 04:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Use upper-case letters, digits and hyphens only.', regex='^[A-Z0-9][A-Z0-9\\-]*$')], verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Use upper-case letters, digits and hyphens only.', regex='^[A-Z0-9][A-Z0-9\\-]*$')], verbose_name='code')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('credits', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='credits')),
                ('level', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Nominal year of study: 100, 200, 300, 400.', verbose_name='level')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive courses stay on record but cannot be offered.', verbose_name='active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_grade', models.CharField(choices=[('A', 'A'), ('A-', 'A−'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B−'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C−'), ('D', 'D'), ('F', 'F')], default='D', help_text='The lowest grade in the prerequisite that satisfies this rule.', max_length=2, verbose_name='minimum grade')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_rules', to='academics.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_for_rules', to='academics.course')),
            ],
            options={
                'verbose_name': 'prerequisite rule',
                'verbose_name_plural': 'prerequisite rules',
                'ordering': ['course__code', 'prerequisite__code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', through='academics.PrerequisiteRule', through_fields=('course', 'prerequisite'), to='academics.course'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use upper-case letters, digits and hyphens only.', regex='^[A-Z0-9][A-Z0-9\\-]*$')], verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('degree_level', models.CharField(choices=[('BACHELOR', "Bachelor's"), ('MASTER', "Master's"), ('DOCTORATE', 'Doctorate')], default='BACHELOR', max_length=10, verbose_name='degree level')),
                ('credits_required', models.PositiveSmallIntegerField(default=144, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='credits required to graduate')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.department')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(help_text='e.g. 01', max_length=5, validators=[django.core.validators.RegexValidator(message='Use upper-case letters, digits and hyphens only.', regex='^[A-Z0-9][A-Z0-9\\-]*$')], verbose_name='section')),
                ('capacity', models.PositiveSmallIntegerField(help_text='Number of seats. Backs rule R6.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='capacity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.course')),
                ('lecturer', models.ForeignKey(blank=True, help_text='Leave blank for a section whose lecturer is still to be announced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='accounts.lecturerprofile')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['term', 'course__code', 'section_code'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day')),
                ('start_time', models.TimeField(verbose_name='starts')),
                ('end_time', models.TimeField(verbose_name='ends')),
                ('room', models.CharField(blank=True, max_length=40, verbose_name='room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='academics.section')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. 2026-FALL', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use upper-case letters, digits and hyphens only.', regex='^[A-Z0-9][A-Z0-9\\-]*$')], verbose_name='code')),
                ('name', models.CharField(help_text='e.g. Fall 2026', max_length=60, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='term starts')),
                ('end_date', models.DateField(verbose_name='term ends')),
                ('registration_opens_at', models.DateTimeField(verbose_name='registration opens')),
                ('registration_closes_at', models.DateTimeField(verbose_name='registration closes')),
                ('is_active', models.BooleanField(default=False, help_text='The term CRS treats as current. Only one term may be current.', verbose_name='current term')),
                ('max_credits_per_student', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='credit ceiling per student')),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academics_term_ends_after_start'), models.CheckConstraint(condition=models.Q(('registration_closes_at__gt', models.F('registration_opens_at'))), name='academics_term_registration_window_ordered'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='academics_term_single_active')],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.term'),
        ),
        migrations.AddConstraint(
            model_name='prerequisiterule',
            constraint=models.UniqueConstraint(fields=('course', 'prerequisite'), name='academics_prerequisite_unique'),
        ),
        migrations.AddConstraint(
            model_name='prerequisiterule',
            constraint=models.CheckConstraint(condition=models.Q(('course', models.F('prerequisite')), _negated=True), name='academics_prerequisite_not_self'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 1)), name='academics_course_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='academics_meeting_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('section', 'day_of_week', 'start_time'), name='academics_meeting_unique_slot'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['term', 'course'], name='academics_section_term_course'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'term', 'section_code'), name='academics_section_unique'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='academics_section_capacity_positive'),
        ),
    ]
