# Generated by Django 5.2.17 on 2026-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisiterule',
            name='minimum_grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], default='D', help_text='The lowest grade in the prerequisite that satisfies this rule.', max_length=2, verbose_name='minimum grade'),
        ),
    ]
